name: 🐞 Bug Report
description: Create a report about something that is not working on the .NET website.
labels: ["bug", "needs-triage"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered ([website-feedback/issues](https://github.com/dotnet/website-feedback/issues?q=is%3Aissue)).
      options:
      - label: I have searched the existing issues
        required: true
  - type: markdown
    attributes:
      value: |
        We welcome bug reports! Please help us gather the information we need to start the triage process.
  - type: textarea
    id: url
    attributes:
      label: URL
      description: In what page are you having issues?
      placeholder: https://dotnet.microsoft.com
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Browser
      description: What is your browser name and version?
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide details about the problem you're experiencing. Include enough details for us to be able to triage it like exact error message, code sample, or anything else that is relevant.
      placeholder: Description
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the bug here.
    validations:
      required: false
